"""add_csv_import_fields

Revision ID: 3d93ca497bd7
Revises: ae2aea8341a8
Create Date: 2025-07-22 00:07:47.745770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = '3d93ca497bd7'
down_revision: Union[str, None] = 'ae2aea8341a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutplan', sa.Column('phase', String(), nullable=True))
    op.add_column('workoutplan', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('workoutplan', sa.Column('rpe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workoutplan', 'rpe')
    op.drop_column('workoutplan', 'week')
    op.drop_column('workoutplan', 'phase')
    # ### end Alembic commands ###
