"""add parsing fields to workout plan

Revision ID: add_parsing_fields
Revises: a1b2c3d4e5f6
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_parsing_fields'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutplan', sa.Column('parsed_type', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_intensity', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_estimated_distance', sa.Float(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_estimated_pace', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_estimated_heart_rate', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_confidence_score', sa.Float(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_main_sets', sa.JSON(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_warmup', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_cooldown', sa.String(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsing_corrections', sa.JSON(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsing_validation_issues', sa.JSON(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsing_validation_score', sa.Float(), nullable=True))
    op.add_column('workoutplan', sa.Column('parsed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workoutplan', 'parsed_at')
    op.drop_column('workoutplan', 'parsing_validation_score')
    op.drop_column('workoutplan', 'parsing_validation_issues')
    op.drop_column('workoutplan', 'parsing_corrections')
    op.drop_column('workoutplan', 'parsed_cooldown')
    op.drop_column('workoutplan', 'parsed_warmup')
    op.drop_column('workoutplan', 'parsed_main_sets')
    op.drop_column('workoutplan', 'parsed_confidence_score')
    op.drop_column('workoutplan', 'parsed_estimated_heart_rate')
    op.drop_column('workoutplan', 'parsed_estimated_pace')
    op.drop_column('workoutplan', 'parsed_estimated_distance')
    op.drop_column('workoutplan', 'parsed_intensity')
    op.drop_column('workoutplan', 'parsed_type')
    # ### end Alembic commands ### 