"""add_training_program_entity

Revision ID: cad68901c5f3
Revises: 3d93ca497bd7
Create Date: 2025-07-23 20:08:06.151823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cad68901c5f3'
down_revision: Union[str, None] = '3d93ca497bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingprogram',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program_type', sa.Enum('MARATHON', 'HALF_MARATHON', 'ULTRA', 'TRAIL', 'ROAD_RACE', 'GENERAL_FITNESS', 'CUSTOM', name='programtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_distance', sa.Float(), nullable=True),
    sa.Column('target_duration', sa.Integer(), nullable=True),
    sa.Column('target_race_date', sa.Date(), nullable=True),
    sa.Column('coach_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='programstatus'), nullable=False),
    sa.Column('program_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # processed_activities may not exist on fresh databases
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'processed_activities' in inspector.get_table_names():
        op.drop_table('processed_activities')
    op.add_column('workoutplan', sa.Column('training_program_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'workoutplan', 'trainingprogram', ['training_program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workoutplan', type_='foreignkey')
    op.drop_column('workoutplan', 'training_program_id')
    op.create_table('processed_activities',
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.drop_table('trainingprogram')
    # ### end Alembic commands ###
