"""add_google_auth_table

Revision ID: e4dce9164f1b
Revises: 1ca3d3b2e6f8
Create Date: 2025-07-23 21:52:42.848520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = 'e4dce9164f1b'
down_revision: Union[str, None] = '1ca3d3b2e6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support GUID type, using VARCHAR instead
    # op.alter_column('googleauth', 'id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # op.alter_column('googleauth', 'user_id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    op.drop_column('googleauth', 'google_name')
    op.drop_column('googleauth', 'google_email')
    op.drop_index('ix_stravaauth_strava_athlete_id', table_name='stravaauth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stravaauth_strava_athlete_id', 'stravaauth', ['strava_athlete_id'], unique=1)
    op.add_column('googleauth', sa.Column('google_email', sa.VARCHAR(), nullable=False))
    op.add_column('googleauth', sa.Column('google_name', sa.VARCHAR(), nullable=False))
    # Note: SQLite doesn't support GUID type, using VARCHAR instead
    # op.alter_column('googleauth', 'user_id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # op.alter_column('googleauth', 'id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
